export default [
    {
        "img": "https://pp.userapi.com/c850216/v850216059/80f5/SR_SubtSqRc.jpg?ava=1",
        "name": "Влад",
        "surname": "Дрозд",
        "description": "Самый красивый парень в БГУИРе, но Оля Н. не ценит :(",
        "gender": "мужской",
        "appearance": 10,
        "intellect": 3,
        "votes": 1,
    },
    {
        "img": "https://pp.userapi.com/c830208/v830208880/11f5d0/bfxesZAe6i4.jpg?ava=1",
        "name": "Андрей",
        "surname": "Беляй",
        "description": "Поёт рандомные песни на задней парте",
        "gender": "мужской",
        "appearance": 4,
        "intellect": 8,
        "votes": 1,
    },
    {
        "img": "https://pp.userapi.com/c845522/v845522768/15ddf9/3gIgfbl6cSU.jpg",
        "name": "Алексей",
        "surname": "Беленко",
        "description": "Похож на миппо, классная стрижка, стрик на Лионе.",
        "gender": "мужской",
        "appearance": 6,
        "intellect": 4,
        "votes": 1,
    },
    {
        "img": "https://pp.userapi.com/c604524/v604524593/f8ac/lZZqkhy-5go.jpg?ava=1",
        "name": "Никита",
        "surname": "Виршич",
        "description": "Не покупает мом на войде",
        "gender": "мужской",
        "appearance": 5,
        "intellect": 9,
        "votes": 1,
    },
    {
        "img": "https://pp.userapi.com/c847017/v847017341/f44f3/T-oV74REsSs.jpg?ava=1",
        "name": "Ульяна",
        "surname": "Козак",
        "description": "Типичный представитель женского пола",
        "gender": "женский",
        "appearance": 6,
        "intellect": 7,
        "votes": 1,
    },

]
